name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      configMigration:
        description: "Toggle PRs for config migration"
        required: false
        default: "true"
        type: choice
        options:
          - "false"
          - "true"
      renovateConfig:
        description: "Define a custom renovate config file"
        required: false
        default: ".github/renovate.json"
        type: string
      minimumReleaseAge:
        description: "Override minimumReleaseAge for a one-time run (e.g., '0 days' to disable delay)"
        required: false
        default: "null"
        type: string
      dryRun:
        description: "Perform a dry run without creating/updating/deleting branches and PRs"
        required: false
        default: "null"
        type: choice
        options:
          - "null"
          - "extract"
          - "lookup"
          - "full"

  schedule:
    - cron: '30 4,6 * * 2-4'

permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: rancher/renovate-config/.github/workflows/renovate-vault.yml@84b669f244ddd0f5fbc7c8f8f63f70820b0c9602 # release
    with:
      configMigration: ${{ github.event.inputs.configMigration || 'true' }}
      logLevel: ${{ github.event.inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule || 'false' }}
      renovateConfig: ${{ github.event.inputs.renovateConfig || '.github/renovate.json' }}
      minimumReleaseAge: ${{ github.event.inputs.minimumReleaseAge || 'null' }}
      dryRun: ${{ github.event.inputs.dryRun || 'null' }}
    secrets:
      override-token: "${{ secrets.RENOVATE_FORK_GH_TOKEN || '' }}"
